import { hashSync } from "bcryptjs";

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

function daysAgo(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
}

function hoursAgo(n: number): Date {
  const d = new Date();
  d.setHours(d.getHours() - n);
  return d;
}

// ---------------------------------------------------------------------------
// Shared password hash (computed once at module load)
// ---------------------------------------------------------------------------

const DEMO_PASSWORD_HASH = hashSync("demo123", 10);

// ---------------------------------------------------------------------------
// Type interfaces matching Prisma schema shapes
// ---------------------------------------------------------------------------

export interface DemoUser {
  id: string;
  email: string;
  passwordHash: string;
  name: string;
  role: "admin" | "closer";
  phone: string | null;
  avatarUrl: string | null;
  commissionType: "percentage" | "flat";
  commissionValue: number;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface DemoPaymentLink {
  id: string;
  closerId: string;
  whopPlanId: string;
  whopProductId: string;
  productName: string;
  purchaseUrl: string;
  planType: string;
  totalAmount: number;
  initialPrice: number;
  renewalPrice: number | null;
  billingPeriodDays: number | null;
  splitPayments: number | null;
  customSplitDescription: string | null;
  currency: string;
  visibility: string;
  status: string;
  title: string | null;
  description: string | null;
  internalNotes: string | null;
  clientName: string | null;
  downPaymentStatus: "fully_paid" | "cancelled" | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface DemoPayment {
  id: string;
  whopPaymentId: string;
  closerId: string;
  paymentLinkId: string | null;
  whopPlanId: string | null;
  whopProductId: string | null;
  productName: string | null;
  customerEmail: string | null;
  customerName: string | null;
  customerId: string | null;
  membershipId: string | null;
  amount: number;
  currency: string;
  status: "succeeded" | "failed" | "refunded" | "pending";
  paidAt: Date | null;
  refundedAt: Date | null;
  refundAmount: number | null;
  installmentNumber: number | null;
  isRecurring: boolean;
  commissionAmount: number | null;
  whopWebhookData: Record<string, unknown> | null;
  zapierStatus: "sent" | "failed" | "skipped" | null;
  zapierError: string | null;
  zapierSentAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface DemoWebhookEvent {
  id: string;
  whopMessageId: string;
  eventType: string;
  payload: Record<string, unknown>;
  processedAt: Date | null;
  error: string | null;
  createdAt: Date;
}

export interface DemoAppSettings {
  id: string;
  whopWebhookId: string | null;
  webhookSecret: string | null;
  webhookUrl: string | null;
  zapierWebhookUrl: string | null;
  enabledProductIds: string[];
  registeredAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface DemoProduct {
  id: string;
  title: string;
  price: number;
}

// ---------------------------------------------------------------------------
// Products
// ---------------------------------------------------------------------------

export const demoProducts: DemoProduct[] = [
  { id: "prod_demo_1", title: "Coaching Program", price: 997 },
  { id: "prod_demo_2", title: "Premium Mentorship", price: 1497 },
  { id: "prod_demo_3", title: "VIP Mastermind", price: 2997 },
];

// ---------------------------------------------------------------------------
// Users
// ---------------------------------------------------------------------------

export const demoUsers: DemoUser[] = [
  {
    id: "user_admin_1",
    email: "demo@closerpay.com",
    passwordHash: DEMO_PASSWORD_HASH,
    name: "Demo Admin",
    role: "admin",
    phone: null,
    avatarUrl: null,
    commissionType: "percentage",
    commissionValue: 0,
    isActive: true,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(60),
  },
  {
    id: "user_closer_1",
    email: "alex@closerpay.com",
    passwordHash: DEMO_PASSWORD_HASH,
    name: "Alex Rivera",
    role: "closer",
    phone: "+1-555-0101",
    avatarUrl: null,
    commissionType: "percentage",
    commissionValue: 15,
    isActive: true,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(45),
  },
  {
    id: "user_closer_2",
    email: "jordan@closerpay.com",
    passwordHash: DEMO_PASSWORD_HASH,
    name: "Jordan Chen",
    role: "closer",
    phone: "+1-555-0202",
    avatarUrl: null,
    commissionType: "flat",
    commissionValue: 50,
    isActive: true,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(40),
  },
];

// ---------------------------------------------------------------------------
// Payment Links (15 total)
// ---------------------------------------------------------------------------

export const demoPaymentLinks: DemoPaymentLink[] = [
  // --- one_time (4) ---
  {
    id: "link_1",
    closerId: "user_closer_1",
    whopPlanId: "plan_demo_ot_1",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    purchaseUrl: "https://whop.com/checkout/demo-plan_ot_1/",
    planType: "one_time",
    totalAmount: 997,
    initialPrice: 997,
    renewalPrice: null,
    billingPeriodDays: null,
    splitPayments: null,
    customSplitDescription: null,
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "Coaching Program - One Time",
    description: null,
    internalNotes: null,
    clientName: "Sarah Johnson",
    downPaymentStatus: null,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(25),
  },
  {
    id: "link_2",
    closerId: "user_closer_1",
    whopPlanId: "plan_demo_ot_2",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    purchaseUrl: "https://whop.com/checkout/demo-plan_ot_2/",
    planType: "one_time",
    totalAmount: 1497,
    initialPrice: 1497,
    renewalPrice: null,
    billingPeriodDays: null,
    splitPayments: null,
    customSplitDescription: null,
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "Premium Mentorship - Full Payment",
    description: null,
    internalNotes: null,
    clientName: "Mike Thompson",
    downPaymentStatus: null,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(22),
  },
  {
    id: "link_3",
    closerId: "user_closer_2",
    whopPlanId: "plan_demo_ot_3",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    purchaseUrl: "https://whop.com/checkout/demo-plan_ot_3/",
    planType: "one_time",
    totalAmount: 997,
    initialPrice: 997,
    renewalPrice: null,
    billingPeriodDays: null,
    splitPayments: null,
    customSplitDescription: null,
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "Coaching Program - One Time",
    description: null,
    internalNotes: null,
    clientName: "Emily Davis",
    downPaymentStatus: null,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
  },
  {
    id: "link_4",
    closerId: "user_closer_2",
    whopPlanId: "plan_demo_ot_4",
    whopProductId: "prod_demo_3",
    productName: "VIP Mastermind",
    purchaseUrl: "https://whop.com/checkout/demo-plan_ot_4/",
    planType: "one_time",
    totalAmount: 2997,
    initialPrice: 2997,
    renewalPrice: null,
    billingPeriodDays: null,
    splitPayments: null,
    customSplitDescription: null,
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "VIP Mastermind - Full Payment",
    description: null,
    internalNotes: null,
    clientName: "David Wilson",
    downPaymentStatus: null,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
  },

  // --- down_payment (3) ---
  {
    id: "link_5",
    closerId: "user_closer_1",
    whopPlanId: "plan_demo_dp_1",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    purchaseUrl: "https://whop.com/checkout/demo-plan_dp_1/",
    planType: "down_payment",
    totalAmount: 1497,
    initialPrice: 497,
    renewalPrice: null,
    billingPeriodDays: null,
    splitPayments: null,
    customSplitDescription: null,
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "Premium Mentorship - Down Payment",
    description: "Down payment of $497 for Premium Mentorship",
    internalNotes: null,
    clientName: "Lisa Anderson",
    downPaymentStatus: "fully_paid",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(10),
  },
  {
    id: "link_6",
    closerId: "user_closer_1",
    whopPlanId: "plan_demo_dp_2",
    whopProductId: "prod_demo_3",
    productName: "VIP Mastermind",
    purchaseUrl: "https://whop.com/checkout/demo-plan_dp_2/",
    planType: "down_payment",
    totalAmount: 2997,
    initialPrice: 997,
    renewalPrice: null,
    billingPeriodDays: null,
    splitPayments: null,
    customSplitDescription: null,
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "VIP Mastermind - Down Payment",
    description: "Down payment of $997 for VIP Mastermind",
    internalNotes: null,
    clientName: "Robert Martinez",
    downPaymentStatus: null,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
  {
    id: "link_7",
    closerId: "user_closer_2",
    whopPlanId: "plan_demo_dp_3",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    purchaseUrl: "https://whop.com/checkout/demo-plan_dp_3/",
    planType: "down_payment",
    totalAmount: 1497,
    initialPrice: 497,
    renewalPrice: null,
    billingPeriodDays: null,
    splitPayments: null,
    customSplitDescription: null,
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "Premium Mentorship - Down Payment",
    description: "Down payment of $497 for Premium Mentorship",
    internalNotes: null,
    clientName: "Jennifer Brown",
    downPaymentStatus: "fully_paid",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(5),
  },

  // --- renewal (3) ---
  {
    id: "link_8",
    closerId: "user_closer_1",
    whopPlanId: "plan_demo_rn_1",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    purchaseUrl: "https://whop.com/checkout/demo-plan_rn_1/",
    planType: "renewal",
    totalAmount: 297,
    initialPrice: 297,
    renewalPrice: 297,
    billingPeriodDays: 30,
    splitPayments: null,
    customSplitDescription: null,
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "Coaching Program - Monthly",
    description: "Monthly coaching subscription",
    internalNotes: null,
    clientName: "Chris Taylor",
    downPaymentStatus: null,
    createdAt: daysAgo(28),
    updatedAt: daysAgo(28),
  },
  {
    id: "link_9",
    closerId: "user_closer_2",
    whopPlanId: "plan_demo_rn_2",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    purchaseUrl: "https://whop.com/checkout/demo-plan_rn_2/",
    planType: "renewal",
    totalAmount: 297,
    initialPrice: 297,
    renewalPrice: 297,
    billingPeriodDays: 30,
    splitPayments: null,
    customSplitDescription: null,
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "Coaching Program - Monthly",
    description: "Monthly coaching subscription",
    internalNotes: null,
    clientName: "Amanda White",
    downPaymentStatus: null,
    createdAt: daysAgo(26),
    updatedAt: daysAgo(26),
  },
  {
    id: "link_10",
    closerId: "user_closer_1",
    whopPlanId: "plan_demo_rn_3",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    purchaseUrl: "https://whop.com/checkout/demo-plan_rn_3/",
    planType: "renewal",
    totalAmount: 497,
    initialPrice: 497,
    renewalPrice: 497,
    billingPeriodDays: 30,
    splitPayments: null,
    customSplitDescription: null,
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "Premium Mentorship - Monthly",
    description: "Monthly mentorship subscription",
    internalNotes: null,
    clientName: "Kevin Lee",
    downPaymentStatus: null,
    createdAt: daysAgo(24),
    updatedAt: daysAgo(24),
  },

  // --- split_pay (3) ---
  {
    id: "link_11",
    closerId: "user_closer_1",
    whopPlanId: "plan_demo_sp_1",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    purchaseUrl: "https://whop.com/checkout/demo-plan_sp_1/",
    planType: "split_pay",
    totalAmount: 1497,
    initialPrice: 499,
    renewalPrice: 499,
    billingPeriodDays: 30,
    splitPayments: 3,
    customSplitDescription: null,
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "Premium Mentorship - 3 Payments",
    description: "3 monthly payments of $499",
    internalNotes: null,
    clientName: "Rachel Green",
    downPaymentStatus: null,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
  },
  {
    id: "link_12",
    closerId: "user_closer_2",
    whopPlanId: "plan_demo_sp_2",
    whopProductId: "prod_demo_3",
    productName: "VIP Mastermind",
    purchaseUrl: "https://whop.com/checkout/demo-plan_sp_2/",
    planType: "split_pay",
    totalAmount: 2997,
    initialPrice: 999,
    renewalPrice: 999,
    billingPeriodDays: 30,
    splitPayments: 3,
    customSplitDescription: null,
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "VIP Mastermind - 3 Payments",
    description: "3 monthly payments of $999",
    internalNotes: null,
    clientName: "Daniel Kim",
    downPaymentStatus: null,
    createdAt: daysAgo(17),
    updatedAt: daysAgo(17),
  },
  {
    id: "link_13",
    closerId: "user_closer_1",
    whopPlanId: "plan_demo_sp_3",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    purchaseUrl: "https://whop.com/checkout/demo-plan_sp_3/",
    planType: "split_pay",
    totalAmount: 997,
    initialPrice: 497,
    renewalPrice: 250,
    billingPeriodDays: 30,
    splitPayments: 3,
    customSplitDescription: null,
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "Coaching Program - 3 Payments",
    description: "Initial $497 then 2 payments of $250",
    internalNotes: null,
    clientName: "Sophia Patel",
    downPaymentStatus: null,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },

  // --- custom_split (2) ---
  {
    id: "link_14",
    closerId: "user_closer_2",
    whopPlanId: "plan_demo_cs_1",
    whopProductId: "prod_demo_3",
    productName: "VIP Mastermind",
    purchaseUrl: "https://whop.com/checkout/demo-plan_cs_1/",
    planType: "custom_split",
    totalAmount: 2997,
    initialPrice: 1497,
    renewalPrice: 750,
    billingPeriodDays: 30,
    splitPayments: 3,
    customSplitDescription: "$1497 upfront, then 2x $750",
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "VIP Mastermind - Custom Split",
    description: "Custom payment plan for VIP Mastermind",
    internalNotes: "Negotiated custom terms",
    clientName: "Marcus Johnson",
    downPaymentStatus: null,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },
  {
    id: "link_15",
    closerId: "user_closer_1",
    whopPlanId: "plan_demo_cs_2",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    purchaseUrl: "https://whop.com/checkout/demo-plan_cs_2/",
    planType: "custom_split",
    totalAmount: 1497,
    initialPrice: 997,
    renewalPrice: 250,
    billingPeriodDays: 30,
    splitPayments: 3,
    customSplitDescription: "$997 upfront, then 2x $250",
    currency: "usd",
    visibility: "quick_link",
    status: "active",
    title: "Premium Mentorship - Custom Split",
    description: "Custom payment plan for Premium Mentorship",
    internalNotes: null,
    clientName: "Olivia Wang",
    downPaymentStatus: null,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
];

// ---------------------------------------------------------------------------
// Payments (27 total)
//
// Commission rules:
//   Alex Rivera  (user_closer_1) -> 15% of amount
//   Jordan Chen  (user_closer_2) -> flat $50
// ---------------------------------------------------------------------------

const customerNames = [
  "Sarah Johnson", "Mike Thompson", "Emily Davis", "David Wilson",
  "Lisa Anderson", "Robert Martinez", "Jennifer Brown", "Chris Taylor",
  "Amanda White", "Kevin Lee", "Rachel Green", "Daniel Kim",
  "Sophia Patel", "Marcus Johnson", "Olivia Wang",
];

function alexCommission(amount: number): number {
  return Math.round(amount * 0.15 * 100) / 100;
}

const JORDAN_COMMISSION = 50;

export const demoPayments: DemoPayment[] = [
  // pay_1: link_1 (one_time, Alex, Coaching $997)
  {
    id: "pay_1",
    whopPaymentId: "whop_pay_demo_1",
    closerId: "user_closer_1",
    paymentLinkId: "link_1",
    whopPlanId: "plan_demo_ot_1",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    customerEmail: "sarah.j@example.com",
    customerName: "Sarah Johnson",
    customerId: "cust_demo_1",
    membershipId: "mem_demo_1",
    amount: 997,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(24),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: null,
    isRecurring: false,
    commissionAmount: alexCommission(997),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(24),
    createdAt: daysAgo(24),
    updatedAt: daysAgo(24),
  },
  // pay_2: link_2 (one_time, Alex, Premium Mentorship $1497)
  {
    id: "pay_2",
    whopPaymentId: "whop_pay_demo_2",
    closerId: "user_closer_1",
    paymentLinkId: "link_2",
    whopPlanId: "plan_demo_ot_2",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    customerEmail: "mike.t@example.com",
    customerName: "Mike Thompson",
    customerId: "cust_demo_2",
    membershipId: "mem_demo_2",
    amount: 1497,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(21),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: null,
    isRecurring: false,
    commissionAmount: alexCommission(1497),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(21),
    createdAt: daysAgo(21),
    updatedAt: daysAgo(21),
  },
  // pay_3: link_3 (one_time, Jordan, Coaching $997)
  {
    id: "pay_3",
    whopPaymentId: "whop_pay_demo_3",
    closerId: "user_closer_2",
    paymentLinkId: "link_3",
    whopPlanId: "plan_demo_ot_3",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    customerEmail: "emily.d@example.com",
    customerName: "Emily Davis",
    customerId: "cust_demo_3",
    membershipId: "mem_demo_3",
    amount: 997,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(19),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: null,
    isRecurring: false,
    commissionAmount: JORDAN_COMMISSION,
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(19),
    createdAt: daysAgo(19),
    updatedAt: daysAgo(19),
  },
  // pay_4: link_4 (one_time, Jordan, VIP Mastermind $2997) - REFUNDED
  {
    id: "pay_4",
    whopPaymentId: "whop_pay_demo_4",
    closerId: "user_closer_2",
    paymentLinkId: "link_4",
    whopPlanId: "plan_demo_ot_4",
    whopProductId: "prod_demo_3",
    productName: "VIP Mastermind",
    customerEmail: "david.w@example.com",
    customerName: "David Wilson",
    customerId: "cust_demo_4",
    membershipId: "mem_demo_4",
    amount: 2997,
    currency: "usd",
    status: "refunded",
    paidAt: daysAgo(17),
    refundedAt: daysAgo(14),
    refundAmount: 2997,
    installmentNumber: null,
    isRecurring: false,
    commissionAmount: JORDAN_COMMISSION,
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(17),
    createdAt: daysAgo(17),
    updatedAt: daysAgo(14),
  },
  // pay_5: link_5 (down_payment, Alex, Premium Mentorship $497 initial)
  {
    id: "pay_5",
    whopPaymentId: "whop_pay_demo_5",
    closerId: "user_closer_1",
    paymentLinkId: "link_5",
    whopPlanId: "plan_demo_dp_1",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    customerEmail: "lisa.a@example.com",
    customerName: "Lisa Anderson",
    customerId: "cust_demo_5",
    membershipId: "mem_demo_5",
    amount: 497,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(14),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 1,
    isRecurring: false,
    commissionAmount: alexCommission(497),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(14),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },
  // pay_6: link_5 remainder (down_payment, Alex, Premium Mentorship $1000 remainder)
  {
    id: "pay_6",
    whopPaymentId: "whop_pay_demo_6",
    closerId: "user_closer_1",
    paymentLinkId: "link_5",
    whopPlanId: "plan_demo_dp_1",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    customerEmail: "lisa.a@example.com",
    customerName: "Lisa Anderson",
    customerId: "cust_demo_5",
    membershipId: "mem_demo_5",
    amount: 1000,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(10),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 2,
    isRecurring: false,
    commissionAmount: alexCommission(1000),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(10),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  // pay_7: link_6 (down_payment, Alex, VIP Mastermind $997 initial - pending, no remainder yet)
  {
    id: "pay_7",
    whopPaymentId: "whop_pay_demo_7",
    closerId: "user_closer_1",
    paymentLinkId: "link_6",
    whopPlanId: "plan_demo_dp_2",
    whopProductId: "prod_demo_3",
    productName: "VIP Mastermind",
    customerEmail: "robert.m@example.com",
    customerName: "Robert Martinez",
    customerId: "cust_demo_6",
    membershipId: "mem_demo_6",
    amount: 997,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(11),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 1,
    isRecurring: false,
    commissionAmount: alexCommission(997),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(11),
    createdAt: daysAgo(11),
    updatedAt: daysAgo(11),
  },
  // pay_8: link_7 (down_payment, Jordan, Premium Mentorship $497 initial)
  {
    id: "pay_8",
    whopPaymentId: "whop_pay_demo_8",
    closerId: "user_closer_2",
    paymentLinkId: "link_7",
    whopPlanId: "plan_demo_dp_3",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    customerEmail: "jennifer.b@example.com",
    customerName: "Jennifer Brown",
    customerId: "cust_demo_7",
    membershipId: "mem_demo_7",
    amount: 497,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(9),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 1,
    isRecurring: false,
    commissionAmount: JORDAN_COMMISSION,
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(9),
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
  },
  // pay_9: link_7 remainder (Jordan, Premium Mentorship $1000 remainder)
  {
    id: "pay_9",
    whopPaymentId: "whop_pay_demo_9",
    closerId: "user_closer_2",
    paymentLinkId: "link_7",
    whopPlanId: "plan_demo_dp_3",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    customerEmail: "jennifer.b@example.com",
    customerName: "Jennifer Brown",
    customerId: "cust_demo_7",
    membershipId: "mem_demo_7",
    amount: 1000,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(5),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 2,
    isRecurring: false,
    commissionAmount: JORDAN_COMMISSION,
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(5),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  // pay_10: link_8 (renewal, Alex, Coaching $297 - first payment)
  {
    id: "pay_10",
    whopPaymentId: "whop_pay_demo_10",
    closerId: "user_closer_1",
    paymentLinkId: "link_8",
    whopPlanId: "plan_demo_rn_1",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    customerEmail: "chris.t@example.com",
    customerName: "Chris Taylor",
    customerId: "cust_demo_8",
    membershipId: "mem_demo_8",
    amount: 297,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(27),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 1,
    isRecurring: true,
    commissionAmount: alexCommission(297),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(27),
    createdAt: daysAgo(27),
    updatedAt: daysAgo(27),
  },
  // pay_11: link_8 (renewal, Alex, Coaching $297 - FAILED renewal)
  {
    id: "pay_11",
    whopPaymentId: "whop_pay_demo_11",
    closerId: "user_closer_1",
    paymentLinkId: "link_8",
    whopPlanId: "plan_demo_rn_1",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    customerEmail: "chris.t@example.com",
    customerName: "Chris Taylor",
    customerId: "cust_demo_8",
    membershipId: "mem_demo_8",
    amount: 297,
    currency: "usd",
    status: "failed",
    paidAt: null,
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 2,
    isRecurring: true,
    commissionAmount: null,
    whopWebhookData: {},
    zapierStatus: "skipped",
    zapierError: null,
    zapierSentAt: null,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  // pay_12: link_9 (renewal, Jordan, Coaching $297 - first payment)
  {
    id: "pay_12",
    whopPaymentId: "whop_pay_demo_12",
    closerId: "user_closer_2",
    paymentLinkId: "link_9",
    whopPlanId: "plan_demo_rn_2",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    customerEmail: "amanda.w@example.com",
    customerName: "Amanda White",
    customerId: "cust_demo_9",
    membershipId: "mem_demo_9",
    amount: 297,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(25),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 1,
    isRecurring: true,
    commissionAmount: JORDAN_COMMISSION,
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(25),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(25),
  },
  // pay_13: link_10 (renewal, Alex, Premium Mentorship $497 - first payment)
  {
    id: "pay_13",
    whopPaymentId: "whop_pay_demo_13",
    closerId: "user_closer_1",
    paymentLinkId: "link_10",
    whopPlanId: "plan_demo_rn_3",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    customerEmail: "kevin.l@example.com",
    customerName: "Kevin Lee",
    customerId: "cust_demo_10",
    membershipId: "mem_demo_10",
    amount: 497,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(23),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 1,
    isRecurring: true,
    commissionAmount: alexCommission(497),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(23),
    createdAt: daysAgo(23),
    updatedAt: daysAgo(23),
  },
  // pay_14: link_11 (split_pay, Alex, Premium Mentorship $499 - installment 1)
  {
    id: "pay_14",
    whopPaymentId: "whop_pay_demo_14",
    closerId: "user_closer_1",
    paymentLinkId: "link_11",
    whopPlanId: "plan_demo_sp_1",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    customerEmail: "rachel.g@example.com",
    customerName: "Rachel Green",
    customerId: "cust_demo_11",
    membershipId: "mem_demo_11",
    amount: 499,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(19),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 1,
    isRecurring: false,
    commissionAmount: alexCommission(499),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(19),
    createdAt: daysAgo(19),
    updatedAt: daysAgo(19),
  },
  // pay_15: link_11 (split_pay, Alex, Premium Mentorship $499 - installment 2)
  {
    id: "pay_15",
    whopPaymentId: "whop_pay_demo_15",
    closerId: "user_closer_1",
    paymentLinkId: "link_11",
    whopPlanId: "plan_demo_sp_1",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    customerEmail: "rachel.g@example.com",
    customerName: "Rachel Green",
    customerId: "cust_demo_11",
    membershipId: "mem_demo_11",
    amount: 499,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(7),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 2,
    isRecurring: false,
    commissionAmount: alexCommission(499),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(7),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  // pay_16: link_12 (split_pay, Jordan, VIP Mastermind $999 - installment 1)
  {
    id: "pay_16",
    whopPaymentId: "whop_pay_demo_16",
    closerId: "user_closer_2",
    paymentLinkId: "link_12",
    whopPlanId: "plan_demo_sp_2",
    whopProductId: "prod_demo_3",
    productName: "VIP Mastermind",
    customerEmail: "daniel.k@example.com",
    customerName: "Daniel Kim",
    customerId: "cust_demo_12",
    membershipId: "mem_demo_12",
    amount: 999,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(16),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 1,
    isRecurring: false,
    commissionAmount: JORDAN_COMMISSION,
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(16),
    createdAt: daysAgo(16),
    updatedAt: daysAgo(16),
  },
  // pay_17: link_12 (split_pay, Jordan, VIP Mastermind $999 - installment 2 - FAILED)
  {
    id: "pay_17",
    whopPaymentId: "whop_pay_demo_17",
    closerId: "user_closer_2",
    paymentLinkId: "link_12",
    whopPlanId: "plan_demo_sp_2",
    whopProductId: "prod_demo_3",
    productName: "VIP Mastermind",
    customerEmail: "daniel.k@example.com",
    customerName: "Daniel Kim",
    customerId: "cust_demo_12",
    membershipId: "mem_demo_12",
    amount: 999,
    currency: "usd",
    status: "failed",
    paidAt: null,
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 2,
    isRecurring: false,
    commissionAmount: null,
    whopWebhookData: {},
    zapierStatus: "skipped",
    zapierError: null,
    zapierSentAt: null,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  // pay_18: link_13 (split_pay, Alex, Coaching $497 - installment 1)
  {
    id: "pay_18",
    whopPaymentId: "whop_pay_demo_18",
    closerId: "user_closer_1",
    paymentLinkId: "link_13",
    whopPlanId: "plan_demo_sp_3",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    customerEmail: "sophia.p@example.com",
    customerName: "Sophia Patel",
    customerId: "cust_demo_13",
    membershipId: "mem_demo_13",
    amount: 497,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(13),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 1,
    isRecurring: false,
    commissionAmount: alexCommission(497),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(13),
    createdAt: daysAgo(13),
    updatedAt: daysAgo(13),
  },
  // pay_19: link_14 (custom_split, Jordan, VIP Mastermind $1497 - installment 1)
  {
    id: "pay_19",
    whopPaymentId: "whop_pay_demo_19",
    closerId: "user_closer_2",
    paymentLinkId: "link_14",
    whopPlanId: "plan_demo_cs_1",
    whopProductId: "prod_demo_3",
    productName: "VIP Mastermind",
    customerEmail: "marcus.j@example.com",
    customerName: "Marcus Johnson",
    customerId: "cust_demo_14",
    membershipId: "mem_demo_14",
    amount: 1497,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(7),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 1,
    isRecurring: false,
    commissionAmount: JORDAN_COMMISSION,
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(7),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  // pay_20: link_15 (custom_split, Alex, Premium Mentorship $997 - installment 1)
  {
    id: "pay_20",
    whopPaymentId: "whop_pay_demo_20",
    closerId: "user_closer_1",
    paymentLinkId: "link_15",
    whopPlanId: "plan_demo_cs_2",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    customerEmail: "olivia.w@example.com",
    customerName: "Olivia Wang",
    customerId: "cust_demo_15",
    membershipId: "mem_demo_15",
    amount: 997,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(4),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 1,
    isRecurring: false,
    commissionAmount: alexCommission(997),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(4),
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  // pay_21: extra one_time Alex, Coaching $997
  {
    id: "pay_21",
    whopPaymentId: "whop_pay_demo_21",
    closerId: "user_closer_1",
    paymentLinkId: null,
    whopPlanId: "plan_demo_extra_1",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    customerEmail: "james.r@example.com",
    customerName: "James Rodriguez",
    customerId: "cust_demo_16",
    membershipId: "mem_demo_16",
    amount: 997,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(16),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: null,
    isRecurring: false,
    commissionAmount: alexCommission(997),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(16),
    createdAt: daysAgo(16),
    updatedAt: daysAgo(16),
  },
  // pay_22: extra one_time Jordan, Premium Mentorship $1497
  {
    id: "pay_22",
    whopPaymentId: "whop_pay_demo_22",
    closerId: "user_closer_2",
    paymentLinkId: null,
    whopPlanId: "plan_demo_extra_2",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    customerEmail: "natalie.s@example.com",
    customerName: "Natalie Smith",
    customerId: "cust_demo_17",
    membershipId: "mem_demo_17",
    amount: 1497,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(13),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: null,
    isRecurring: false,
    commissionAmount: JORDAN_COMMISSION,
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(13),
    createdAt: daysAgo(13),
    updatedAt: daysAgo(13),
  },
  // pay_23: extra one_time Alex, VIP Mastermind $2997 - REFUNDED
  {
    id: "pay_23",
    whopPaymentId: "whop_pay_demo_23",
    closerId: "user_closer_1",
    paymentLinkId: null,
    whopPlanId: "plan_demo_extra_3",
    whopProductId: "prod_demo_3",
    productName: "VIP Mastermind",
    customerEmail: "tom.h@example.com",
    customerName: "Tom Henderson",
    customerId: "cust_demo_18",
    membershipId: "mem_demo_18",
    amount: 2997,
    currency: "usd",
    status: "refunded",
    paidAt: daysAgo(8),
    refundedAt: daysAgo(6),
    refundAmount: 2997,
    installmentNumber: null,
    isRecurring: false,
    commissionAmount: alexCommission(2997),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(8),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(6),
  },
  // pay_24: extra renewal Jordan, Coaching $297
  {
    id: "pay_24",
    whopPaymentId: "whop_pay_demo_24",
    closerId: "user_closer_2",
    paymentLinkId: "link_9",
    whopPlanId: "plan_demo_rn_2",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    customerEmail: "amanda.w@example.com",
    customerName: "Amanda White",
    customerId: "cust_demo_9",
    membershipId: "mem_demo_9",
    amount: 297,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(2),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 2,
    isRecurring: true,
    commissionAmount: JORDAN_COMMISSION,
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(2),
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  // pay_25: recent Alex, Premium Mentorship $497 renewal
  {
    id: "pay_25",
    whopPaymentId: "whop_pay_demo_25",
    closerId: "user_closer_1",
    paymentLinkId: "link_10",
    whopPlanId: "plan_demo_rn_3",
    whopProductId: "prod_demo_2",
    productName: "Premium Mentorship",
    customerEmail: "kevin.l@example.com",
    customerName: "Kevin Lee",
    customerId: "cust_demo_10",
    membershipId: "mem_demo_10",
    amount: 497,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(1),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 2,
    isRecurring: true,
    commissionAmount: alexCommission(497),
    whopWebhookData: {},
    zapierStatus: "sent",
    zapierError: null,
    zapierSentAt: daysAgo(1),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  // pay_26: recent pending payment - Alex
  {
    id: "pay_26",
    whopPaymentId: "whop_pay_demo_26",
    closerId: "user_closer_1",
    paymentLinkId: "link_13",
    whopPlanId: "plan_demo_sp_3",
    whopProductId: "prod_demo_1",
    productName: "Coaching Program",
    customerEmail: "sophia.p@example.com",
    customerName: "Sophia Patel",
    customerId: "cust_demo_13",
    membershipId: "mem_demo_13",
    amount: 250,
    currency: "usd",
    status: "pending",
    paidAt: null,
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 2,
    isRecurring: false,
    commissionAmount: null,
    whopWebhookData: {},
    zapierStatus: null,
    zapierError: null,
    zapierSentAt: null,
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
  },
  // pay_27: zapier failed payment - Jordan
  {
    id: "pay_27",
    whopPaymentId: "whop_pay_demo_27",
    closerId: "user_closer_2",
    paymentLinkId: "link_14",
    whopPlanId: "plan_demo_cs_1",
    whopProductId: "prod_demo_3",
    productName: "VIP Mastermind",
    customerEmail: "marcus.j@example.com",
    customerName: "Marcus Johnson",
    customerId: "cust_demo_14",
    membershipId: "mem_demo_14",
    amount: 750,
    currency: "usd",
    status: "succeeded",
    paidAt: daysAgo(1),
    refundedAt: null,
    refundAmount: null,
    installmentNumber: 2,
    isRecurring: false,
    commissionAmount: JORDAN_COMMISSION,
    whopWebhookData: {},
    zapierStatus: "failed",
    zapierError: "Connection timeout to Zapier webhook",
    zapierSentAt: null,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

// ---------------------------------------------------------------------------
// Webhook Events (7)
// ---------------------------------------------------------------------------

export const demoWebhookEvents: DemoWebhookEvent[] = [
  {
    id: "wh_1",
    whopMessageId: "whop_msg_demo_1",
    eventType: "payment.succeeded",
    payload: { payment_id: "whop_pay_demo_1", amount: 997, status: "succeeded" },
    processedAt: daysAgo(24),
    error: null,
    createdAt: daysAgo(24),
  },
  {
    id: "wh_2",
    whopMessageId: "whop_msg_demo_2",
    eventType: "payment.succeeded",
    payload: { payment_id: "whop_pay_demo_2", amount: 1497, status: "succeeded" },
    processedAt: daysAgo(21),
    error: null,
    createdAt: daysAgo(21),
  },
  {
    id: "wh_3",
    whopMessageId: "whop_msg_demo_3",
    eventType: "payment.succeeded",
    payload: { payment_id: "whop_pay_demo_3", amount: 997, status: "succeeded" },
    processedAt: daysAgo(19),
    error: null,
    createdAt: daysAgo(19),
  },
  {
    id: "wh_4",
    whopMessageId: "whop_msg_demo_4",
    eventType: "payment.refunded",
    payload: { payment_id: "whop_pay_demo_4", amount: 2997, status: "refunded" },
    processedAt: daysAgo(14),
    error: null,
    createdAt: daysAgo(14),
  },
  {
    id: "wh_5",
    whopMessageId: "whop_msg_demo_5",
    eventType: "payment.failed",
    payload: { payment_id: "whop_pay_demo_11", amount: 297, status: "failed" },
    processedAt: daysAgo(3),
    error: null,
    createdAt: daysAgo(3),
  },
  {
    id: "wh_6",
    whopMessageId: "whop_msg_demo_6",
    eventType: "payment.succeeded",
    payload: { payment_id: "whop_pay_demo_25", amount: 497, status: "succeeded" },
    processedAt: daysAgo(1),
    error: null,
    createdAt: daysAgo(1),
  },
  {
    id: "wh_7",
    whopMessageId: "whop_msg_demo_7",
    eventType: "payment.succeeded",
    payload: { payment_id: "whop_pay_demo_27", amount: 750, status: "succeeded" },
    processedAt: null,
    error: "Zapier webhook delivery failed",
    createdAt: daysAgo(1),
  },
];

// ---------------------------------------------------------------------------
// App Settings (singleton)
// ---------------------------------------------------------------------------

export const demoAppSettings: DemoAppSettings = {
  id: "default",
  whopWebhookId: "demo_webhook_id",
  webhookSecret: "demo_webhook_secret",
  webhookUrl: "https://demo.closerpay.com/api/webhooks/whop",
  zapierWebhookUrl: "https://hooks.zapier.com/hooks/catch/demo/123456/",
  enabledProductIds: ["prod_demo_1", "prod_demo_2", "prod_demo_3"],
  registeredAt: daysAgo(60),
  createdAt: daysAgo(60),
  updatedAt: daysAgo(1),
};
